In [1]:
import pandas as pd
import numpy as np

In [5]:
# list folders in a directory 
import os
data_dir = 'F:/CODEX/AI_clinic_class/All_images'
folders = os.listdir(data_dir)
img_files = []

for folder in folders:
    folder_path = os.path.join(data_dir, folder)
    if os.path.isdir(folder_path):
        files = os.listdir(folder_path)
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff')):
                img_files.append(os.path.join(folder, file))
print(img_files)

['t_010\\01_01_01.bmp', 't_010\\01_01_02.BMP', 't_010\\01_01_03.BMP', 't_010\\01_01_04.BMP', 't_010\\01_01_05.BMP', 't_010\\01_01_06.BMP', 't_010\\01_01_07.bmp', 't_010\\01_02_01.BMP', 't_010\\01_02_02.BMP', 't_010\\01_02_04.BMP', 't_010\\01_02_05.BMP', 't_010\\01_02_06.BMP', 't_010\\01_02_07.bmp', 't_010\\01_02_08.BMP', 't_010\\01_02_09.bmp', 't_010\\01_02_10.BMP', 't_010\\01_02_11.BMP', 't_010\\01_02_12.BMP', 't_010\\01_02_13.BMP', 't_010\\01_02_15.BMP', 't_010\\01_02_17.bmp', 't_010\\01_02_18.BMP', 't_010\\01_02_19.BMP', 't_010\\01_02_20.BMP', 't_010\\01_02_21.bmp', 't_010\\01_02_22.BMP', 't_010\\01_02_23.BMP', 't_010\\01_02_24.BMP', 't_010\\01_02_25.bmp', 't_010\\01_02_26.BMP', 't_010\\01_02_30.bmp', 't_010\\01_03_01.BMP', 't_010\\01_03_02.BMP', 't_010\\01_03_03.BMP', 't_010\\01_03_04.BMP', 't_010\\01_03_05.BMP', 't_010\\01_03_06.BMP', 't_010\\01_03_07.BMP', 't_010\\01_03_08.BMP', 't_010\\01_04_01.bmp', 't_010\\01_04_02.BMP', 't_010\\01_04_03.bmp', 't_010\\01_04_04.BMP', 't_010\\02_01_01.bmp', 't_010\\02_01_02.bmp', 't_010\\02_01_03.BMP', 't_010\\02_01_04.bmp', 't_010\\02_01_05.bmp', 't_010\\02_01_06.bmp', 't_010\\02_01_07.BMP', 't_010\\02_01_08.BMP', 't_010\\02_01_09.BMP', 't_010\\02_01_10.BMP', 't_010\\02_01_11.BMP', 't_010\\02_01_12.bmp', 't_010\\02_01_13.bmp', 't_010\\02_01_14.BMP', 't_010\\02_01_15.BMP', 't_010\\02_01_16.BMP', 't_010\\02_01_17.BMP', 't_010\\02_01_18.BMP', 't_010\\02_01_19.BMP', 't_010\\02_01_20.BMP', 't_010\\02_01_21.BMP', 't_010\\02_01_22.BMP', 't_010\\02_01_23.BMP', 't_010\\02_01_24.BMP', 't_010\\02_01_25.BMP', 't_010\\02_01_26.BMP', 't_010\\02_01_27.BMP', 't_010\\02_02_01.bmp', 't_010\\02_02_02.bmp', 't_010\\02_02_03.bmp', 't_010\\02_02_04.bmp', 't_010\\02_02_05.BMP', 't_010\\02_02_06.BMP', 't_010\\02_02_07.BMP', 't_010\\02_02_08.BMP', 't_010\\02_02_09.bmp', 't_010\\02_02_10.BMP', 't_010\\02_02_11.BMP', 't_010\\02_02_12.bmp', 't_010\\02_02_13.BMP', 't_010\\02_02_14.BMP', 't_010\\02_02_15.BMP', 't_010\\02_02_16.BMP', 't_010\\02_02_17.BMP', 't_010\\02_02_18.BMP', 't_010\\02_02_19.BMP', 't_010\\02_02_20.bmp', 't_010\\02_02_21.BMP', 't_010\\02_02_22.bmp', 't_010\\02_03_01.BMP', 't_010\\02_03_02.BMP', 't_010\\03_01_01.BMP', 't_010\\03_01_02.BMP', 't_010\\03_01_03.bmp', 't_010\\03_01_04.BMP', 't_010\\03_01_05.BMP', 't_010\\03_01_06.bmp', 't_010\\03_01_07.BMP', 't_010\\03_01_08.BMP', 't_010\\03_01_09.BMP', 't_010\\03_01_10.BMP', 't_010\\03_01_11.BMP', 't_010\\03_01_12.BMP', 't_010\\03_01_14.bmp', 't_010\\03_02_01.BMP', 't_010\\03_02_02.BMP', 't_010\\03_02_03.BMP', 't_010\\03_02_04.BMP', 't_010\\03_02_05.BMP', 't_010\\03_02_06.BMP', 't_010\\03_02_07.BMP', 't_010\\03_02_08.bmp', 't_010\\03_02_09.bmp', 't_010\\03_02_10.BMP', 't_010\\03_02_11.BMP', 't_010\\03_02_12.BMP', 't_010\\03_02_13.BMP', 't_010\\03_02_14.BMP', 't_010\\03_02_15.BMP', 't_010\\03_03_01.BMP', 't_010\\03_03_02.BMP', 't_010\\03_03_03.BMP', 't_010\\03_03_04.BMP', 't_010\\03_03_05.BMP', 't_010\\03_03_06.BMP', 't_010\\03_03_07.BMP', 't_010\\03_03_08.BMP', 't_010\\03_03_09.bmp', 't_010\\03_03_10.BMP', 't_010\\03_03_11.BMP', 't_010\\03_03_12.BMP', 't_010\\03_03_13.BMP', 't_010\\03_03_14.BMP', 't_010\\03_04_01.BMP', 't_010\\03_04_02.bmp', 't_010\\03_04_03.BMP', 't_010\\03_04_04.BMP', 't_010\\03_04_05.BMP', 't_010\\03_04_06.BMP', 't_010\\03_04_07.BMP', 't_010\\03_04_08.BMP', 't_010\\03_04_09.bmp', 't_010\\03_04_10.BMP', 't_010\\03_04_11.BMP', 't_010\\03_04_12.BMP', 't_010\\03_04_13.BMP', 't_010\\03_04_14.BMP', 't_010\\03_04_15.bmp', 't_010\\03_04_16.BMP', 't_010\\04_01_01.BMP', 't_010\\04_01_02.BMP', 't_010\\04_01_03.bmp', 't_010\\04_01_04.BMP', 't_010\\04_01_05.BMP', 't_010\\04_01_06.bmp', 't_010\\04_01_07.bmp', 't_010\\04_02_01.BMP', 't_010\\04_02_02.bmp', 't_010\\04_02_03.bmp', 't_010\\04_02_04.BMP', 't_010\\04_03_01.bmp', 't_010\\04_03_02.BMP', 't_010\\04_03_03.BMP', 't_010\\04_03_04.BMP', 't_010\\04_03_05.BMP', 't_010\\04_03_06.BMP', 't_010\\04_03_07.bmp', 't_010\\04_03_08.bmp', 't_010\\04_03_09.bmp', 't_010\\04_03_10.BMP', 't_010\\04_03_11.BMP', 't_010\\04_04_01.BMP', 't_010\\04_04_02.BMP', 't_010\\04_04_03.bmp', 't_010\\04_04_04.BMP', 't_010\\04_04_05.BMP', 't_010\\04_04_06.BMP', 't_010\\04_04_07.BMP', 't_010\\04_04_08.bmp', 't_010\\04_04_09.BMP', 't_010\\04_04_10.BMP', 't_010\\04_04_11.BMP', 't_010\\04_04_12.BMP', 't_010\\04_05_01.bmp', 't_010\\04_05_02.bmp', 't_010\\05_01_01.BMP', 't_010\\05_01_02.BMP', 't_010\\05_01_03.BMP', 't_010\\05_01_04.BMP', 't_010\\05_01_05.BMP', 't_010\\05_01_06.BMP', 't_010\\05_01_07.BMP', 't_010\\05_01_08.BMP', 't_010\\05_01_09.BMP', 't_010\\05_01_10.BMP', 't_010\\05_01_11.BMP', 't_010\\05_01_12.BMP', 't_010\\05_01_13.BMP', 't_010\\05_01_14.BMP', 't_010\\05_01_15.BMP', 't_010\\05_01_16.BMP', 't_010\\05_01_17.BMP', 't_010\\05_01_18.BMP', 't_010\\05_01_19.BMP', 't_010\\05_01_20.BMP', 't_010\\05_01_21.BMP', 't_010\\05_02_01.BMP', 't_010\\05_02_03.BMP', 't_010\\05_02_04.BMP', 't_010\\05_02_13.bmp', 't_010\\05_03_01.BMP', 't_010\\05_03_02.BMP', 't_010\\05_03_03.BMP', 't_010\\05_03_04.BMP', 't_010\\05_03_05.BMP', 't_010\\05_03_06.BMP', 't_010\\05_03_07.BMP', 't_010\\05_03_08.BMP', 't_010\\05_03_09.BMP', 't_010\\05_03_10.BMP', 't_010\\05_03_11.BMP', 't_010\\05_03_12.BMP', 't_010\\05_03_13.BMP', 't_010\\05_03_14.BMP', 't_010\\05_04_01.BMP', 't_010\\05_04_02.BMP', 't_010\\05_04_03.bmp', 't_010\\05_05_02.BMP', 't_010\\05_05_03.BMP', 't_010\\05_05_04.bmp', 't_010\\05_05_05.bmp', 't_010\\05_06_01.bmp', 't_010\\05_06_02.BMP', 't_010\\05_06_03.bmp', 't_010\\05_06_16.bmp', 't_010\\05_06_42.bmp', 't_010\\05_06_43.bmp', 't_010\\05_06_44.bmp', 't_010\\05_06_45.bmp', 't_010\\05_07_01.bmp', 't_010\\05_07_02.bmp', 't_010\\05_07_03.bmp', 't_010\\05_07_04.bmp', 't_010\\05_07_05.bmp', 't_010\\05_07_06.bmp', 't_010\\05_07_23.bmp', 't_010\\05_07_79.bmp', 't_010\\05_08_01.bmp', 't_010\\05_08_02.bmp', 't_010\\05_08_03.bmp', 't_010\\05_09_01.bmp', 't_010\\05_09_02.bmp', 't_010\\05_09_10.bmp', 't_010\\05_10_01.bmp', 't_010\\05_10_05.bmp', 't_010\\05_10_06.bmp', 't_010\\05_10_07.bmp', 't_010\\05_10_08.bmp', 't_010\\05_10_09.bmp', 't_010\\05_10_10.bmp', 't_010\\05_10_12.bmp', 't_010\\05_11_03.bmp', 't_010\\05_12_02.bmp', 't_010\\05_12_03.bmp', 't_010\\05_12_04.bmp', 't_010\\05_12_05.bmp', 't_010\\05_12_06.bmp', 't_010\\05_12_07.bmp', 't_010\\05_12_08.bmp', 't_010\\05_12_09.bmp', 't_010\\05_12_10.bmp', 't_010\\05_12_11.bmp', 't_010\\05_12_12.bmp', 't_010\\05_12_13.bmp', 't_010\\05_12_14.bmp', 't_010\\05_12_15.bmp', 't_010\\05_12_46.bmp', 't_010\\05_13_01.bmp', 't_010\\05_13_02.bmp', 't_010\\05_13_03.bmp', 't_010\\05_13_04.bmp', 't_010\\05_13_05.bmp', 't_010\\05_13_06.bmp', 't_010\\05_13_07.bmp', 't_010\\05_13_08.bmp', 't_010\\05_13_09.bmp', 't_010\\05_14_01.bmp', 't_010\\05_14_02.bmp', 't_010\\05_14_03.bmp', 't_010\\05_14_04.bmp', 't_010\\05_15_01.bmp', 't_010\\05_15_02.bmp', 't_010\\05_15_03.bmp', 't_010\\05_15_04.bmp', 't_010\\05_15_05.bmp', 't_010\\05_15_06.bmp', 't_010\\06_01_01.bmp', 't_010\\06_01_02.BMP', 't_010\\06_01_03.BMP', 't_010\\06_01_04.BMP', 't_010\\07_01_01.BMP', 't_010\\07_01_02.BMP', 't_010\\07_01_03.BMP', 't_010\\07_01_04.BMP', 't_010\\07_01_05.BMP', 't_010\\07_01_06.bmp', 't_010\\07_01_07.BMP', 't_010\\07_01_08.BMP', 't_010\\07_01_09.BMP', 't_010\\07_01_10.BMP', 't_010\\07_01_11.BMP', 't_010\\07_01_12.BMP', 't_010\\07_01_13.BMP', 't_010\\07_01_14.BMP', 't_010\\07_01_15.BMP', 't_010\\07_01_16.BMP', 't_010\\07_01_17.BMP', 't_010\\07_01_18.BMP', 't_010\\07_01_19.BMP', 't_010\\08_01_01.BMP', 't_010\\08_01_02.BMP', 't_010\\08_01_03.BMP', 't_010\\08_01_04.BMP', 't_010\\08_01_05.BMP', 't_010\\09_00_01.BMP', 't_010\\09_00_02.BMP', 't_010\\09_00_03.BMP', 't_010\\09_00_04.BMP', 't_010\\09_00_05.BMP', 't_010\\09_00_06.BMP', 't_010\\09_00_07.BMP', 't_010\\09_00_08.BMP', 't_010\\09_00_09.BMP', 't_010\\09_00_10.BMP', 't_010\\09_00_11.BMP', 't_010\\09_00_12.BMP', 't_010\\09_00_13.BMP', 't_010\\09_00_14.BMP', 't_010\\09_00_15.BMP', 't_010\\09_00_16.BMP', 't_010\\09_00_17.BMP', 't_010\\09_00_18.BMP', 't_010\\09_00_19.BMP', 't_010\\10_00_00.BMP', 't_010\\X.010.A.01.jpg', 't_010\\X.010.A.03.jpg', 't_010\\X.010.A.04.jpg', 't_010\\X.010.A.jpg', 't_010\\X.010.B.01.jpg', 't_010\\X.010.B.02.jpg', 't_010\\X.010.B.03+.jpg', 't_010\\X.010.B.04.jpg', 't_010\\X.010.B.08.jpg', 't_010\\X.010.B.09.jpg', 't_010\\X.010.B.11.jpg', 't_010\\X.010.B.12.jpg', 't_010\\X.010.B.13.jpg', 't_010\\X.010.B.15.jpg', 't_010\\X.010.B.16.jpg', 't_010\\X.010.B.17.jpg', 't_010\\X.010.B.18.jpg', 't_010\\X.010.B.19.jpg', 't_010\\X.010.B.20.jpg', 't_010\\X.010.B.21.jpg', 't_010\\X.010.B.23.jpg', 't_010\\X.010.B.25.jpg', 't_010\\X.010.B.26.jpg', 't_010\\X.010.B.27.jpg', 't_010\\X.010.B.28.jpg', 't_010\\X.010.B.29+.jpg', 't_010\\X.010.B.31.jpg', 't_010\\X.010.B.32.jpg', 't_010\\X.010.B.jpg', 't_010\\X.010.C.01.jpg', 't_010\\X.010.C.02.jpg', 't_010\\X.010.C.04.jpg', 't_010\\X.010.C.05.jpg', 't_010\\X.010.C.06.jpg', 't_010\\X.010.C.07.jpg', 't_010\\X.010.C.08.jpg', 't_010\\X.010.C.09.jpg', 't_010\\X.010.C.10.jpg', 't_010\\X.010.C.11.jpg', 't_010\\X.010.C.14.jpg', 't_010\\X.010.C.jpg', 't_010\\X.010.D.01.jpg', 't_010\\X.010.D.02.jpg', 't_010\\X.010.D.03.jpg', 't_010\\X.010.D.04.jpg', 't_010\\X.010.D.05.jpg', 't_010\\X.010.D.06.jpg', 't_010\\X.010.D.07.jpg', 't_010\\X.010.D.08.jpg', 't_010\\X.010.D.09.jpg', 't_010\\X.010.D.10.jpg', 't_010\\X.010.D.11.jpg', 't_010\\X.010.D.12.jpg', 't_010\\X.010.D.13.jpg', 't_010\\X.010.D.14.jpg', 't_010\\X.010.D.15.jpg', 't_010\\X.010.D.16.jpg', 't_010\\X.010.D.17.jpg', 't_010\\X.010.D.18.jpg', 't_010\\X.010.D.19.jpg', 't_010\\X.010.D.21.jpg', 't_010\\X.010.D.22.jpg', 't_010\\X.010.D.23.jpg', 't_010\\X.010.D.24.jpg', 't_010\\X.010.D.25.jpg', 't_010\\X.010.D.27.jpg', 't_010\\X.010.D.jpg', 't_010\\X.010.E.01.jpg', 't_010\\X.010.E.02.jpg', 't_010\\X.010.E.03.jpg', 't_010\\X.010.E.04.jpg', 't_010\\X.010.E.05.jpg', 't_010\\X.010.E.06.jpg', 't_010\\X.010.E.07.jpg', 't_010\\X.010.E.08.jpg', 't_010\\X.010.E.09.jpg', 't_010\\X.010.E.10.jpg', 't_010\\X.010.E.11.jpg', 't_010\\X.010.E.12.jpg', 't_010\\X.010.E.13.jpg', 't_010\\X.010.E.14.jpg', 't_010\\X.010.E.15.jpg', 't_010\\X.010.E.16.jpg', 't_010\\X.010.E.17.jpg', 't_010\\X.010.E.18+.jpg', 't_010\\X.010.E.20.jpg', 't_010\\X.010.E.21.jpg', 't_010\\X.010.E.22+.jpg', 't_010\\X.010.E.22.jpg', 't_010\\X.010.E.23.jpg', 't_010\\X.010.E.jpg', 't_010\\X.010.F$c.jpg', 't_010\\X.010.F.01.jpg', 't_010\\X.010.F.02.jpg', 't_010\\X.010.F.03.jpg', 't_010\\X.010.F.04.jpg', 't_010\\X.010.F.05+.jpg', 't_010\\X.010.F.07.jpg', 't_010\\X.010.F.08.jpg', 't_010\\X.010.F.09.jpg', 't_010\\X.010.F.10.jpg', 't_010\\X.010.F.11.jpg', 't_010\\X.010.F.12.jpg', 't_010\\X.010.F.13.jpg', 't_010\\X.010.F.14.jpg', 't_010\\X.010.F.15+.jpg', 't_010\\X.010.F.17.jpg', 't_010\\X.010.F.18.jpg', 't_010\\X.010.F.19.jpg', 't_010\\X.010.F.20.jpg', 't_010\\X.010.F.21+.jpg', 't_010\\X.010.F.24.jpg', 't_010\\X.010.F.25.jpg', 't_010\\X.010.F.26.jpg', 't_010\\X.010.F.27.jpg', 't_010\\X.010.F.28.jpg', 't_010\\X.010.F.29.jpg', 't_010\\X.010.F.30.jpg', 't_010\\X.010.F.31.jpg', 't_010\\X.010.F.32.jpg', 't_010\\X.010.F.33.jpg', 't_010\\X.010.F.34.jpg', 't_010\\X.010.F.35.jpg', 't_010\\X.010.F.36.jpg', 't_010\\X.010.F.37.jpg', 't_010\\X.010.F.39.jpg', 't_010\\X.010.F.41.jpg', 't_010\\X.010.F.42.jpg', 't_010\\X.010.F.43.jpg', 't_010\\X.010.F.jpg', 't_010\\X.010.G.01.jpg', 't_010\\X.010.G.02+.jpg', 't_010\\X.010.G.04.jpg', 't_010\\X.010.G.05.jpg', 't_010\\X.010.G.06.jpg', 't_010\\X.010.G.07.jpg', 't_010\\X.010.G.08.jpg', 't_010\\X.010.G.09.jpg', 't_010\\X.010.G.11.jpg', 't_010\\X.010.G.12.jpg', 't_010\\X.010.G.13.jpg', 't_010\\X.010.G.14.jpg', 't_010\\X.010.G.15.jpg', 't_010\\X.010.G.16+.jpg', 't_010\\X.010.G.16.jpg', 't_010\\X.010.G.17.jpg', 't_010\\X.010.G.18.jpg', 't_010\\X.010.G.19.jpg', 't_010\\X.010.G.20.jpg', 't_010\\X.010.G.21.jpg', 't_010\\X.010.G.22.jpg', 't_010\\X.010.G.23.jpg', 't_010\\X.010.G.jpg', 't_010\\X.010.H.02.jpg', 't_010\\X.010.H.03.jpg', 't_010\\X.010.H.04+.jpg', 't_010\\X.010.H.05.jpg', 't_010\\X.010.H.06.jpg', 't_010\\X.010.H.07.jpg', 't_010\\X.010.H.08.jpg', 't_010\\X.010.H.09.jpg', 't_010\\X.010.H.11.jpg', 't_010\\X.010.H.12.jpg', 't_010\\X.010.H.13.jpg', 't_010\\X.010.H.14.jpg', 't_010\\X.010.H.15.jpg', 't_010\\X.010.H.16.jpg', 't_010\\X.010.H.17.jpg', 't_010\\X.010.H.18.jpg', 't_010\\X.010.H.jpg', 't_010\\X.010.I.01.jpg', 't_010\\X.010.I.02.jpg', 't_010\\X.010.I.03.jpg', 't_010\\X.010.I.04.jpg', 't_010\\X.010.I.05.jpg', 't_010\\X.010.I.06.jpg', 't_010\\X.010.I.07.jpg', 't_010\\X.010.I.08.jpg', 't_010\\X.010.I.09.jpg', 't_010\\X.010.I.10.jpg', 't_010\\X.010.I.11.jpg', 't_010\\X.010.I.12.jpg', 't_010\\X.010.I.13.jpg', 't_010\\X.010.I.14.jpg', 't_010\\X.010.I.15.jpg', 't_010\\X.010.I.16.jpg', 't_010\\X.010.I.17.jpg', 't_010\\X.010.I.18.jpg', 't_010\\X.010.I.19.jpg', 't_010\\X.010.I.20.jpg', 't_010\\X.010.I.21.jpg', 't_010\\X.010.I.22.jpg', 't_010\\X.010.I.23.jpg', 't_010\\X.010.I.24.jpg', 't_010\\X.010.I.25.jpg', 't_010\\X.010.I.26.jpg', 't_010\\X.010.I.27.jpg', 't_010\\X.010.I.28.jpg', 't_010\\X.010.I.29.jpg', 't_010\\X.010.I.30.jpg', 't_010\\X.010.I.31.jpg', 't_010\\X.010.I.32.jpg', 't_010\\X.010.I.33.jpg', 't_010\\X.010.I.34+.jpg', 't_010\\X.010.I.34.jpg', 't_010\\X.010.I.35.jpg', 't_010\\X.010.I.36.jpg', 't_010\\X.010.I.37.jpg', 't_010\\X.010.I.38.jpg', 't_010\\X.010.I.39.jpg', 't_010\\X.010.I.40.jpg', 't_010\\X.010.I.41.jpg', 't_010\\X.010.I.42.jpg', 't_010\\X.010.I.jpg', 't_010\\X.010.jpg', 't_010\\X.010.Z.01.jpg', 't_010\\X.010.Z.02.jpg', 't_010\\X.010.Z.jpg', 't_010\\X.011.A.02.jpg', 't_010\\X.011.A.03+.jpg', 't_010\\X.011.A.07.jpg', 't_010\\X.011.A.09+.jpg', 't_010\\X.011.A.10.jpg', 't_010\\X.011.A.15.jpg', 't_010\\X.011.A.17.jpg', 't_010\\X.011.A.19+.jpg', 't_010\\X.011.A.23.jpg', 't_010\\X.011.A.24.jpg', 't_010\\X.011.A.jpg', 't_010\\X.011.B.01.jpg', 't_010\\X.011.B.02.jpg', 't_010\\X.011.B.05.jpg', 't_010\\X.011.B.06.jpg', 't_010\\X.011.B.08.jpg', 't_010\\X.011.B.10.jpg', 't_010\\X.011.B.11.jpg', 't_010\\X.011.B.12.jpg', 't_010\\X.011.B.13.jpg', 't_010\\X.011.B.15.jpg', 't_010\\X.011.B.18.jpg', 't_010\\X.011.B.20.jpg', 't_010\\X.011.B.22.jpg', 't_010\\X.011.B.jpg', 't_010\\X.011.C.01.jpg', 't_010\\X.011.C.03.jpg', 't_010\\X.011.C.05.jpg', 't_010\\X.011.C.06.jpg', 't_010\\X.011.C.09.jpg', 't_010\\X.011.C.10.jpg', 't_010\\X.011.C.jpg', 't_010\\X.011.D.01.jpg', 't_010\\X.011.D.02.jpg', 't_010\\X.011.D.03.jpg', 't_010\\X.011.D.04.jpg', 't_010\\X.011.D.06+.jpg', 't_010\\X.011.D.10.jpg', 't_010\\X.011.D.13+.jpg', 't_010\\X.011.D.15.jpg', 't_010\\X.011.D.17.jpg', 't_010\\X.011.D.18.jpg', 't_010\\X.011.D.21.jpg', 't_010\\X.011.D.jpg', 't_010\\X.011.jpg', 't_010\\X.011.Z.jpg', 't_010\\X.012.A.01+.jpg', 't_010\\X.012.A.03.jpg', 't_010\\X.012.A.04.jpg', 't_010\\X.012.A.05.jpg', 't_010\\X.012.A.07+.jpg', 't_010\\X.012.A.08+.jpg', 't_010\\X.012.A.09.jpg', 't_010\\X.012.A.10.jpg', 't_010\\X.012.A.11.jpg', 't_010\\X.012.A.13.jpg', 't_010\\X.012.A.15.jpg', 't_010\\X.012.A.17.jpg', 't_010\\X.012.A.19.jpg', 't_010\\X.012.A.21.jpg', 't_010\\X.012.A.23.jpg', 't_010\\X.012.A.26.jpg', 't_010\\X.012.A.27.jpg', 't_010\\X.012.A.28.jpg', 't_010\\X.012.A.31.jpg', 't_010\\X.012.A.32.jpg', 't_010\\X.012.A.36.jpg', 't_010\\X.012.A.37.jpg', 't_010\\X.012.A.38.jpg', 't_010\\X.012.A.40.jpg', 't_010\\X.012.A.42.jpg', 't_010\\X.012.A.43.jpg', 't_010\\X.012.A.45.jpg', 't_010\\X.012.A.jpg', 't_010\\X.012.B.02.jpg', 't_010\\X.012.B.05.jpg', 't_010\\X.012.B.07.jpg', 't_010\\X.012.B.09.jpg', 't_010\\X.012.B.10.jpg', 't_010\\X.012.B.13.jpg', 't_010\\X.012.B.18.jpg', 't_010\\X.012.B.19+.jpg', 't_010\\X.012.B.22.jpg', 't_010\\X.012.B.24.jpg', 't_010\\X.012.B.25.jpg', 't_010\\X.012.B.29+.jpg', 't_010\\X.012.B.29.jpg', 't_010\\X.012.B.31.jpg', 't_010\\X.012.B.34.jpg', 't_010\\X.012.B.35.jpg', 't_010\\X.012.B.38.jpg', 't_010\\X.012.B.39.jpg', 't_010\\X.012.B.41.jpg', 't_010\\X.012.B.42.jpg', 't_010\\X.012.B.43.jpg', 't_010\\X.012.B.44.jpg', 't_010\\X.012.B.45.jpg', 't_010\\X.012.B.47.jpg', 't_010\\X.012.B.49.jpg', 't_010\\X.012.B.50.jpg', 't_010\\X.012.B.52.jpg', 't_010\\X.012.B.53.jpg', 't_010\\X.012.B.56.jpg', 't_010\\X.012.B.57.jpg', 't_010\\X.012.B.58.jpg', 't_010\\X.012.B.60.jpg', 't_010\\X.012.B.62.jpg', 't_010\\X.012.B.64+.jpg', 't_010\\X.012.B.64.jpg', 't_010\\X.012.B.66.jpg', 't_010\\X.012.B.68+.jpg', 't_010\\X.012.B.jpg', 't_010\\X.012.C.02.jpg', 't_010\\X.012.C.06.jpg', 't_010\\X.012.C.08.jpg', 't_010\\X.012.C.09.jpg', 't_010\\X.012.C.11.jpg', 't_010\\X.012.C.12.jpg', 't_010\\X.012.C.14.jpg', 't_010\\X.012.C.16.jpg', 't_010\\X.012.C.17.jpg', 't_010\\X.012.C.19.jpg', 't_010\\X.012.C.21.jpg', 't_010\\X.012.C.23.jpg', 't_010\\X.012.C.24.jpg', 't_010\\X.012.C.26.jpg', 't_010\\X.012.C.28.jpg', 't_010\\X.012.C.30.jpg', 't_010\\X.012.C.32.jpg', 't_010\\X.012.C.33.jpg', 't_010\\X.012.C.34.jpg', 't_010\\X.012.C.36.jpg', 't_010\\X.012.C.jpg', 't_010\\X.012.D.01.jpg', 't_010\\X.012.D.02.jpg', 't_010\\X.012.D.04.jpg', 't_010\\X.012.D.05.jpg', 't_010\\X.012.D.06.jpg', 't_010\\X.012.D.08.jpg', 't_010\\X.012.D.11.jpg', 't_010\\X.012.D.12.jpg', 't_010\\X.012.D.14.jpg', 't_010\\X.012.D.16.jpg', 't_010\\X.012.D.18.jpg', 't_010\\X.012.D.20.jpg', 't_010\\X.012.D.21.jpg', 't_010\\X.012.D.23.jpg', 't_010\\X.012.D.24+.jpg', 't_010\\X.012.D.25.jpg', 't_010\\X.012.D.27.jpg', 't_010\\X.012.D.29.jpg', 't_010\\X.012.D.31.jpg', 't_010\\X.012.D.33.jpg', 't_010\\X.012.D.34.jpg', 't_010\\X.012.D.36+.jpg', 't_010\\X.012.D.37.jpg', 't_010\\X.012.D.40.jpg', 't_010\\X.012.D.42.jpg', 't_010\\X.012.D.44.jpg', 't_010\\X.012.D.46.jpg', 't_010\\X.012.D.49.jpg', 't_010\\X.012.D.51.jpg', 't_010\\X.012.D.53.jpg', 't_010\\X.012.D.54.jpg', 't_010\\X.012.D.55.jpg', 't_010\\X.012.D.56.jpg', 't_010\\X.012.D.58.jpg', 't_010\\X.012.D.60.jpg', 't_010\\X.012.D.63.jpg', 't_010\\X.012.D.64.jpg', 't_010\\X.012.D.66.jpg', 't_010\\X.012.D.68.jpg', 't_010\\X.012.D.70.jpg', 't_010\\X.012.D.71.jpg', 't_010\\X.012.D.74.jpg', 't_010\\X.012.D.76+.jpg', 't_010\\X.012.D.79.jpg', 't_010\\X.012.D.jpg', 't_010\\X.012.jpg', 't_010\\X.012.Z.01.jpg', 't_010\\X.012.Z.02.jpg', 't_010\\X.012.Z.03.jpg', 't_010\\X.012.Z.04.jpg', 't_010\\X.012.Z.jpg', 't_010\\X.013.A.01.jpg', 't_010\\X.013.A.02.jpg', 't_010\\X.013.A.04+.jpg', 't_010\\X.013.A.07.jpg', 't_010\\X.013.A.08.jpg', 't_010\\X.013.A.10.jpg', 't_010\\X.013.A.11.jpg', 't_010\\X.013.A.14.jpg', 't_010\\X.013.A.15.jpg', 't_010\\X.013.A.jpg', 't_010\\X.013.jpg', 't_010\\X.013.Z.jpg', 't_010\\X.020.A.01.jpg', 't_010\\X.020.A.04.jpg', 't_010\\X.020.A.05.jpg', 't_010\\X.020.A.07.jpg', 't_010\\X.020.A.08.jpg', 't_010\\X.020.A.10.jpg', 't_010\\X.020.A.11.jpg', 't_010\\X.020.A.12.jpg', 't_010\\X.020.A.13.jpg', 't_010\\X.020.A.14.jpg', 't_010\\X.020.A.15.jpg', 't_010\\X.020.A.16.jpg', 't_010\\X.020.A.17.jpg', 't_010\\X.020.A.18.jpg', 't_010\\X.020.A.20.jpg', 't_010\\X.020.A.21.jpg', 't_010\\X.020.A.22.jpg', 't_010\\X.020.A.23.jpg', 't_010\\X.020.A.24.jpg', 't_010\\X.020.A.25.jpg', 't_010\\X.020.A.26.jpg', 't_010\\X.020.A.28.jpg', 't_010\\X.020.A.29.jpg', 't_010\\X.020.A.30.jpg', 't_010\\X.020.A.32.jpg', 't_010\\X.020.A.33.jpg', 't_010\\X.020.A.34.jpg', 't_010\\X.020.A.35.jpg', 't_010\\X.020.A.37.jpg', 't_010\\X.020.A.38.jpg', 't_010\\X.020.A.jpg', 't_010\\X.020.B.01.jpg', 't_010\\X.020.B.02.jpg', 't_010\\X.020.B.05.jpg', 't_010\\X.020.B.07.jpg', 't_010\\X.020.B.09.jpg', 't_010\\X.020.B.11.jpg', 't_010\\X.020.B.12.jpg', 't_010\\X.020.B.14+.jpg', 't_010\\X.020.B.16.jpg', 't_010\\X.020.B.18.jpg', 't_010\\X.020.B.19.jpg', 't_010\\X.020.B.20.jpg', 't_010\\X.020.B.21.jpg', 't_010\\X.020.B.22.jpg', 't_010\\X.020.B.23.jpg', 't_010\\X.020.B.24.jpg', 't_010\\X.020.B.25.jpg', 't_010\\X.020.B.26.jpg', 't_010\\X.020.B.jpg', 't_010\\X.020.C.01.jpg', 't_010\\X.020.C.02.jpg', 't_010\\X.020.C.05.jpg', 't_010\\X.020.C.06.jpg', 't_010\\X.020.C.07.jpg', 't_010\\X.020.C.09.jpg', 't_010\\X.020.C.10.jpg', 't_010\\X.020.C.12.jpg', 't_010\\X.020.C.13.jpg', 't_010\\X.020.C.14+.jpg', 't_010\\X.020.C.15.jpg', 't_010\\X.020.C.16.jpg', 't_010\\X.020.C.18.jpg', 't_010\\X.020.C.20.jpg', 't_010\\X.020.C.23.jpg', 't_010\\X.020.C.24.jpg', 't_010\\X.020.C.26.jpg', 't_010\\X.020.C.29.jpg', 't_010\\X.020.C.31.jpg', 't_010\

In [6]:
df = pd.read_csv("../data_csv/training_data_relative_paths.csv")
df

,glyph_image,elements_original,full_image_path,20,21?,?,??,?_01,?_02,?_03,...,zacatl,zacuan,zahualli,zahuatl,zayolin,zo,zolin,zoquitl,zoyatl,zozoma
0,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,glyphs/Unsorted\X.010.A.01-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,X.010.B.08-1.jpg,acatl|huitztli|tepetl,glyphs/Unsorted\X.010.B.08-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,X.010.B.12-1.jpg,nopalli,glyphs/Unsorted\X.010.B.12-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,X.010.B.19-1.jpg,pantli|oztotl,glyphs/Unsorted\X.010.B.19-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,X.010.B.23-1.jpg,tetl|oztotl|petlatl,glyphs/Unsorted\X.010.B.23-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,376_13r_12-17.jpg,cuauhtli,glyphs/Unsorted\376_13r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4988,376_14r_06-17.jpg,cuauhtli,glyphs/Unsorted\376_14r_06-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4989,376_14r_12-17.jpg,cuauhtli,glyphs/Unsorted\376_14r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4990,376_21v_01-17.jpg,cuauhtli,glyphs/Unsorted\376_21v_01-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4991,376_21v_17-17.jpg,cuauhtli,glyphs/Unsorted\376_21v_17-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df["full_image_path"] = df["full_image_path"].apply(lambda x: x.replace("\\", "/"))
df

,glyph_image,elements_original,full_image_path,20,21?,?,??,?_01,?_02,?_03,...,zacatl,zacuan,zahualli,zahuatl,zayolin,zo,zolin,zoquitl,zoyatl,zozoma
0,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,glyphs/Unsorted/X.010.A.01-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,X.010.B.08-1.jpg,acatl|huitztli|tepetl,glyphs/Unsorted/X.010.B.08-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,X.010.B.12-1.jpg,nopalli,glyphs/Unsorted/X.010.B.12-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,X.010.B.19-1.jpg,pantli|oztotl,glyphs/Unsorted/X.010.B.19-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,X.010.B.23-1.jpg,tetl|oztotl|petlatl,glyphs/Unsorted/X.010.B.23-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,376_13r_12-17.jpg,cuauhtli,glyphs/Unsorted/376_13r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4988,376_14r_06-17.jpg,cuauhtli,glyphs/Unsorted/376_14r_06-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4989,376_14r_12-17.jpg,cuauhtli,glyphs/Unsorted/376_14r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4990,376_21v_01-17.jpg,cuauhtli,glyphs/Unsorted/376_21v_01-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4991,376_21v_17-17.jpg,cuauhtli,glyphs/Unsorted/376_21v_17-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Create New Training Data from All_images Folder

Now we'll create a new training dataset using the relationships_updated.csv and matching images from the All_images folder.

In [9]:
# Load the relationships_updated.csv file
relationships_df = pd.read_csv("../data_csv/relationships_updated.csv")
print(f"Relationships data shape: {relationships_df.shape}")
print(f"\nColumns: {relationships_df.columns.tolist()}")
print(f"\nFirst few rows:")
relationships_df.head(10)

Relationships data shape: (44577, 10)

Columns: ['Unnamed: 0', 'codex_id', 'codex_titre', 'glyph_id', 'glyph_cote', 'glyph_lecture', 'element_id', 'element_name', 'element_theme', 'glyph_image']

First few rows:

,Unnamed: 0,codex_id,codex_titre,glyph_id,glyph_cote,glyph_lecture,element_id,element_name,element_theme,glyph_image
0,0,1,XOLOTL,1.0,X.010.A.01,tenamitec,584,tetl,04.04.01,X.010.A.01-1.jpg
1,1,1,XOLOTL,1.0,X.010.A.01,tenamitec,747,xocpalmachiyotl,01.04.03,X.010.A.01-1.jpg
2,2,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,472,petlatl,05.02.03,X.010.A.03-1.jpg
3,3,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,193,cuahuitl_1,03.01.01,X.010.A.03-1.jpg
4,4,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,161,comitl,05.03.01,X.010.A.03-1.jpg
5,5,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,685,tototl,02.01.13,X.010.A.04-1.jpg
6,6,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,570,tepetl,04.03.08,X.010.A.04-1.jpg
7,7,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,75,atl,04.05.01,X.010.A.04-1.jpg
8,8,1,XOLOTL,4.0,X.010.B.01,zacatlan,776,zacatl,03.02.08,X.010.B.01-1.jpg
9,9,1,XOLOTL,4.0,X.010.B.01,zacatlan,624,tlanelhuatl,03.04.10,X.010.B.01-1.jpg

In [10]:
# Create a mapping of all available images in All_images folder
# img_files already contains the list of images from All_images
image_lookup = {}
for img_path in img_files:
    # Extract just the filename (e.g., "X.010.A.01-1.jpg")
    filename = os.path.basename(img_path)
    image_lookup[filename] = img_path

print(f"Total images found in All_images: {len(image_lookup)}")
print(f"\nSample image mappings:")
for i, (filename, path) in enumerate(list(image_lookup.items())[:5]):
    print(f"{filename} -> {path}")

Total images found in All_images: 41051

Sample image mappings:
01_01_01.bmp -> t_totomi\01_01_01.bmp
01_01_02.BMP -> t_010\01_01_02.BMP
01_01_03.BMP -> t_010\01_01_03.BMP
01_01_04.BMP -> t_010\01_01_04.BMP
01_01_05.BMP -> t_010\01_01_05.BMP

In [11]:
# Load the elements.csv to get all unique elements (these will be our columns)
elements_df = pd.read_csv("../data_csv/elements.csv")
unique_elements = sorted(elements_df['element'].unique())
print(f"Total unique elements: {len(unique_elements)}")
print(f"\nFirst 10 elements: {unique_elements[:10]}")

Total unique elements: 785

First 10 elements: ['20', '21?', '?', '??', '?_01', '?_02', '?_03', '?_04', '?_05', '?_06']

In [12]:
# Group relationships by glyph_image to get all elements for each image
glyph_elements = relationships_df.groupby('glyph_image')['element_name'].apply(list).to_dict()

print(f"Total unique glyph images in relationships: {len(glyph_elements)}")
print(f"\nSample glyph with elements:")
for i, (glyph, elements) in enumerate(list(glyph_elements.items())[:3]):
    print(f"{glyph}: {elements}")

Total unique glyph images in relationships: 23285

Sample glyph with elements:
026r_A_01-2.jpg: ['xilotl']
026r_A_02-2.jpg: ['miztli', 'xayacatl']
026r_A_05-2.jpg: ['ocelotl']

In [13]:
# Create the new training data
training_data = []

for glyph_image, element_list in glyph_elements.items():
    # Check if the image exists in All_images folder
    if glyph_image in image_lookup:
        # Create the row with image path and elements
        row = {
            'glyph_image': glyph_image,
            'elements_original': '|'.join(element_list),  # Store as pipe-separated string
            'full_image_path': f"All_images/{image_lookup[glyph_image]}"
        }
        
        # Add binary columns for each element (1 if present, 0 if not)
        for element in unique_elements:
            row[element] = 1 if element in element_list else 0
        
        training_data.append(row)

# Create the DataFrame
new_training_df = pd.DataFrame(training_data)

print(f"New training data shape: {new_training_df.shape}")
print(f"Old training data shape: {df.shape}")
print(f"\nImages found: {len(new_training_df)}")
print(f"Images not found: {len(glyph_elements) - len(new_training_df)}")

New training data shape: (0, 0)
Old training data shape: (4992, 788)

Images found: 0
Images not found: 23285

In [14]:
# Debug: Check the mismatch between filenames
print("Sample glyph_image from relationships:")
sample_glyph_names = list(glyph_elements.keys())[:10]
for name in sample_glyph_names:
    print(f"  {name}")

print("\nSample filenames from All_images:")
sample_image_names = list(image_lookup.keys())[:10]
for name in sample_image_names:
    print(f"  {name}")

Sample glyph_image from relationships:
  026r_A_01-2.jpg
  026r_A_02-2.jpg
  026r_A_05-2.jpg
  026r_A_06-2.jpg
  026r_A_07-2.jpg
  026r_A_08-2.jpg
  026r_A_09-2.jpg
  026r_A_10-2.jpg
  026r_A_11-2.jpg
  026r_A_12-2.jpg

Sample filenames from All_images:
  01_01_01.bmp
  01_01_02.BMP
  01_01_03.BMP
  01_01_04.BMP
  01_01_05.BMP
  01_01_06.BMP
  01_01_07.bmp
  01_02_01.BMP
  01_02_02.BMP
  01_02_04.BMP

In [15]:
# Check the old training data structure
print("Sample from old training data (glyphs folder):")
print(df[['glyph_image', 'full_image_path']].head(10))

Sample from old training data (glyphs folder):
        glyph_image                   full_image_path
0  X.010.A.01-1.jpg  glyphs/Unsorted/X.010.A.01-1.jpg
1  X.010.B.08-1.jpg  glyphs/Unsorted/X.010.B.08-1.jpg
2  X.010.B.12-1.jpg  glyphs/Unsorted/X.010.B.12-1.jpg
3  X.010.B.19-1.jpg  glyphs/Unsorted/X.010.B.19-1.jpg
4  X.010.B.23-1.jpg  glyphs/Unsorted/X.010.B.23-1.jpg
5  X.010.C.04-1.jpg  glyphs/Unsorted/X.010.C.04-1.jpg
6  X.010.C.10-1.jpg  glyphs/Unsorted/X.010.C.10-1.jpg
7  X.010.D.05-1.jpg  glyphs/Unsorted/X.010.D.05-1.jpg
8  X.010.D.14-1.jpg  glyphs/Unsorted/X.010.D.14-1.jpg
9  X.010.D.16-1.jpg  glyphs/Unsorted/X.010.D.16-1.jpg

In [16]:
# Check if files from old training data exist in All_images
test_files = df['glyph_image'].head(20).tolist()
found_count = 0
for test_file in test_files:
    if test_file in image_lookup:
        found_count += 1
        print(f"✓ Found: {test_file} -> {image_lookup[test_file]}")
    else:
        print(f"✗ NOT found: {test_file}")

print(f"\nFound {found_count}/{len(test_files)} files from old training data")

✗ NOT found: X.010.A.01-1.jpg
✗ NOT found: X.010.B.08-1.jpg
✗ NOT found: X.010.B.12-1.jpg
✗ NOT found: X.010.B.19-1.jpg
✗ NOT found: X.010.B.23-1.jpg
✗ NOT found: X.010.C.04-1.jpg
✗ NOT found: X.010.C.10-1.jpg
✗ NOT found: X.010.D.05-1.jpg
✗ NOT found: X.010.D.14-1.jpg
✗ NOT found: X.010.D.16-1.jpg
✗ NOT found: X.010.D.23-1.jpg
✗ NOT found: X.010.E.06-1.jpg
✗ NOT found: X.010.E.07-1.jpg
✗ NOT found: X.010.E.20-1.jpg
✗ NOT found: X.010.F.11-1.jpg
✗ NOT found: X.010.F.14-1.jpg
✗ NOT found: X.010.G.14-1.jpg
✗ NOT found: X.010.H.08-1.jpg
✗ NOT found: X.010.H.14-1.jpg
✗ NOT found: X.010.H.16-1.jpg

Found 0/20 files from old training data

In [ ]:
# Let's explore what's in All_images more carefully
# Check the actual folder structure
print("Folders in All_images:")
folders_in_all_images = [f for f in folders if os.path.isdir(os.path.join(data_dir, f))]
print(f"Total folders: {len(folders_in_all_images)}")
print(f"Sample folders: {folders_in_all_images[:20]}")

In [17]:
# Verify the pattern: glyph_cote + "-" + codex_id
# The glyph_image column should already be in this format
print("Checking glyph_image format in relationships_updated.csv:")
print(relationships_df[['glyph_cote', 'codex_id', 'glyph_image']].head(10))

# Verify if the pattern matches
sample_row = relationships_df.iloc[0]
expected_filename = f"{sample_row['glyph_cote']}-{sample_row['codex_id']}.jpg"
print(f"\nExpected: {expected_filename}")
print(f"Actual:   {sample_row['glyph_image']}")

Checking glyph_image format in relationships_updated.csv:
   glyph_cote  codex_id       glyph_image
0  X.010.A.01         1  X.010.A.01-1.jpg
1  X.010.A.01         1  X.010.A.01-1.jpg
2  X.010.A.03         1  X.010.A.03-1.jpg
3  X.010.A.03         1  X.010.A.03-1.jpg
4  X.010.A.03         1  X.010.A.03-1.jpg
5  X.010.A.04         1  X.010.A.04-1.jpg
6  X.010.A.04         1  X.010.A.04-1.jpg
7  X.010.A.04         1  X.010.A.04-1.jpg
8  X.010.B.01         1  X.010.B.01-1.jpg
9  X.010.B.01         1  X.010.B.01-1.jpg

Expected: X.010.A.01-1.jpg
Actual:   X.010.A.01-1.jpg

In [18]:
# Search for files that might match the pattern
# Let's look for any file containing "X.010" or similar patterns
print("Looking for files with 'X.010' pattern:")
matching_files = [f for f in image_lookup.keys() if 'X' in f or 'x' in f]
print(f"Files with 'X' or 'x': {len(matching_files)}")
if matching_files:
    print(f"Sample: {matching_files[:20]}")
else:
    # Try looking for files with dots
    dot_files = [f for f in list(image_lookup.keys())[:100] if '.' in f]
    print(f"\nFiles with dots: {len(dot_files)}")
    if dot_files:
        print(f"Sample: {dot_files[:20]}")

Looking for files with 'X.010' pattern:
Files with 'X' or 'x': 2585
Sample: ['X.010.A.01.jpg', 'X.010.A.03.jpg', 'X.010.A.04.jpg', 'X.010.A.jpg', 'X.010.B.01.jpg', 'X.010.B.02.jpg', 'X.010.B.03+.jpg', 'X.010.B.04.jpg', 'X.010.B.08.jpg', 'X.010.B.09.jpg', 'X.010.B.11.jpg', 'X.010.B.12.jpg', 'X.010.B.13.jpg', 'X.010.B.15.jpg', 'X.010.B.16.jpg', 'X.010.B.17.jpg', 'X.010.B.18.jpg', 'X.010.B.19.jpg', 'X.010.B.20.jpg', 'X.010.B.21.jpg']

In [19]:
# Create an enhanced lookup that can match by glyph_cote pattern
# Map by both full filename and by glyph_cote pattern
enhanced_lookup = {}

for filename, path in image_lookup.items():
    # Store by exact filename
    enhanced_lookup[filename] = path
    
    # Also create entries for partial matches (e.g., "X.010.A.01" from "X.010.A.01.jpg")
    base_name = filename.rsplit('.', 1)[0]  # Remove extension
    enhanced_lookup[base_name] = path

print(f"Enhanced lookup size: {len(enhanced_lookup)}")

# Test with a sample
test_glyph = "X.010.A.01-1.jpg"
test_cote = "X.010.A.01"
print(f"\nTest lookup for '{test_glyph}': {test_glyph in enhanced_lookup}")
print(f"Test lookup for '{test_cote}': {test_cote in enhanced_lookup}")
if test_cote in enhanced_lookup:
    print(f"  -> {enhanced_lookup[test_cote]}")

Enhanced lookup size: 81817

Test lookup for 'X.010.A.01-1.jpg': False
Test lookup for 'X.010.A.01': True
  -> t_010\X.010.A.01.jpg

In [20]:
# Recreate training data using glyph_cote for matching
training_data_new = []

for glyph_image, element_list in glyph_elements.items():
    # Extract glyph_cote from glyph_image (e.g., "X.010.A.01-1.jpg" -> "X.010.A.01")
    # This should match the format in the relationships
    glyph_cote = relationships_df[relationships_df['glyph_image'] == glyph_image]['glyph_cote'].iloc[0] if glyph_image in relationships_df['glyph_image'].values else None
    
    if glyph_cote and glyph_cote in enhanced_lookup:
        # Create the row with image path and elements
        row = {
            'glyph_image': glyph_image,
            'elements_original': '|'.join(element_list),
            'full_image_path': f"All_images/{enhanced_lookup[glyph_cote]}"
        }
        
        # Add binary columns for each element
        for element in unique_elements:
            row[element] = 1 if element in element_list else 0
        
        training_data_new.append(row)

# Create the DataFrame
new_training_df = pd.DataFrame(training_data_new)

print(f"✓ New training data shape: {new_training_df.shape}")
print(f"  Old training data shape: {df.shape}")
print(f"\n✓ Images found: {len(new_training_df)}")
print(f"✗ Images not found: {len(glyph_elements) - len(new_training_df)}")

✓ New training data shape: (21952, 788)
  Old training data shape: (4992, 788)

✓ Images found: 21952
✗ Images not found: 1333

In [21]:
# Display sample of new training data
print("Sample rows from new training data:")
new_training_df.head(10)

Sample rows from new training data:

,glyph_image,elements_original,full_image_path,20,21?,?,??,?_01,?_02,?_03,...,zacatl,zacuan,zahualli,zahuatl,zayolin,zo,zolin,zoquitl,zoyatl,zozoma
0,026r_A_01-2.jpg,xilotl,All_images/t_026\026r_A_01.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,026r_A_02-2.jpg,miztli|xayacatl,All_images/t_026\026r_A_02.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,026r_A_05-2.jpg,ocelotl,All_images/t_026\026r_A_05.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,026r_A_06-2.jpg,tepetl|tlalli,All_images/t_026\026r_A_06.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,026r_A_07-2.jpg,atl|apantli,All_images/t_026\026r_A_07.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,026r_A_08-2.jpg,tlalli|calli,All_images/t_026\026r_A_08.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,026r_A_09-2.jpg,tlalli|atl|cilli|chalchihuitl|itzcuintli,All_images/t_026\026r_A_09.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,026r_A_10-2.jpg,tlalli|atl|chalchihuitl|cilli,All_images/t_026\026r_A_10.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,026r_A_11-2.jpg,tlalli|tetl|tlapalli,All_images/t_026\026r_A_11.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,026r_A_12-2.jpg,tlalli|huauhtli,All_images/t_026\026r_A_12.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
# Save the new training data to CSV
output_path = "../data_csv/training_data_all_images.csv"
new_training_df.to_csv(output_path, index=False)
print(f"New training data saved to: {output_path}")
print(f"Total rows: {len(new_training_df)}")
print(f"Total columns: {len(new_training_df.columns)}")

New training data saved to: ../data_csv/training_data_all_images.csv
Total rows: 21952
Total columns: 788

In [23]:
# Comparison statistics
print("=" * 60)
print("COMPARISON: Old vs New Training Data")
print("=" * 60)
print(f"Old dataset (from glyphs folder): {len(df)} images")
print(f"New dataset (from All_images folder): {len(new_training_df)} images")
print(f"Difference: {len(new_training_df) - len(df)} more images")
print(f"\nPercentage increase: {((len(new_training_df) - len(df)) / len(df) * 100):.2f}%")
print("=" * 60)

# Check which images from relationships are missing
missing_images = [img for img in glyph_elements.keys() if img not in image_lookup]
print(f"\nImages in relationships but not found in All_images: {len(missing_images)}")
if missing_images[:10]:
    print(f"Sample missing images: {missing_images[:10]}")

============================================================
COMPARISON: Old vs New Training Data
============================================================
Old dataset (from glyphs folder): 4992 images
New dataset (from All_images folder): 21952 images
Difference: 16960 more images

Percentage increase: 339.74%
============================================================

Images in relationships but not found in All_images: 23285
Sample missing images: ['026r_A_01-2.jpg', '026r_A_02-2.jpg', '026r_A_05-2.jpg', '026r_A_06-2.jpg', '026r_A_07-2.jpg', '026r_A_08-2.jpg', '026r_A_09-2.jpg', '026r_A_10-2.jpg', '026r_A_11-2.jpg', '026r_A_12-2.jpg']

In [24]:
# Verify a few sample images exist
print("Verifying sample image paths:")
sample_paths = new_training_df['full_image_path'].head(5).tolist()
for path in sample_paths:
    full_path = os.path.join('F:/CODEX/AI_clinic_class', path)
    exists = os.path.exists(full_path)
    status = "✓" if exists else "✗"
    print(f"{status} {path}")

Verifying sample image paths:
✓ All_images/t_026\026r_A_01.jpg
✓ All_images/t_026\026r_A_02.jpg
✓ All_images/t_026\026r_A_05.jpg
✓ All_images/t_026\026r_A_06.jpg
✓ All_images/t_026\026r_A_07.jpg