In [1]:
import pandas as pd

In [49]:
df = pd.read_csv('relationships.csv')
df.head()

,codex_id,codex_titre,glyph_id,glyph_cote,glyph_lecture,element_id,element_name,element_theme,glyph_image
0,1,XOLOTL,1.0,X.010.A.01,tenamitec,1,tetl,04.04.01,X.010.A.01-1.jpg
1,1,XOLOTL,1.0,X.010.A.01,tenamitec,2,xocpalmachiyotl,01.04.03,X.010.A.01-1.jpg
2,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,3,petlatl,05.02.03,X.010.A.03-1.jpg
3,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,4,cuahuitl_1,03.01.01,X.010.A.03-1.jpg
4,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,5,comitl,05.03.01,X.010.A.03-1.jpg

In [50]:
df.isna().sum()

codex_id            0
codex_titre         0
glyph_id          578
glyph_cote          0
glyph_lecture    1137
element_id          0
element_name        0
element_theme       0
glyph_image         0
dtype: int64

In [51]:
df[df.glyph_image.str.contains("--")]

,codex_id,codex_titre,glyph_id,glyph_cote,glyph_lecture,element_id,element_name,element_theme,glyph_image
12,1,XOLOTL,6.0,X.010.B.03-,tamazolac teopan zaca...,13,zacatl,03.02.08,X.010.B.03--1.jpg
13,1,XOLOTL,6.0,X.010.B.03-,tamazolac teopan zaca...,14,tzacualli,05.01.08,X.010.B.03--1.jpg
14,1,XOLOTL,6.0,X.010.B.03-,tamazolac teopan zaca...,15,tamazolin,02.02.18,X.010.B.03--1.jpg
15,1,XOLOTL,6.0,X.010.B.03-,tamazolac teopan zaca...,16,atl,04.05.01,X.010.B.03--1.jpg
16,1,XOLOTL,6.0,X.010.B.03-,tamazolac teopan zaca...,17,artefact_09,05.01.21,X.010.B.03--1.jpg
...,...,...,...,...,...,...,...,...,...
5124,1,XOLOTL,2318.0,X.101.C.12-,acatentehuatzin,5125,tentetl,05.06.03,X.101.C.12--1.jpg
5125,1,XOLOTL,2318.0,X.101.C.12-,acatentehuatzin,5126,tetl,04.04.01,X.101.C.12--1.jpg
5156,1,XOLOTL,2329.0,X.101.H.02-,tlalnepantla tenco,5157,tlalli,04.03.01,X.101.H.02--1.jpg
5157,1,XOLOTL,2329.0,X.101.H.02-,tlalnepantla tenco,5158,tlantli,01.02.19,X.101.H.02--1.jpg
5158,1,XOLOTL,2329.0,X.101.H.02-,tlalnepantla tenco,5159,tentli,01.02.18,X.101.H.02--1.jpg

In [52]:
df.glyph_image = df.glyph_image.apply(lambda x: x.replace("--", "-"))

In [53]:
df[df.glyph_image.str.contains("--")]

Empty DataFrame
Columns: [codex_id, codex_titre, glyph_id, glyph_cote, glyph_lecture, element_id, element_name, element_theme, glyph_image]
Index: []

In [54]:
df.head()

,codex_id,codex_titre,glyph_id,glyph_cote,glyph_lecture,element_id,element_name,element_theme,glyph_image
0,1,XOLOTL,1.0,X.010.A.01,tenamitec,1,tetl,04.04.01,X.010.A.01-1.jpg
1,1,XOLOTL,1.0,X.010.A.01,tenamitec,2,xocpalmachiyotl,01.04.03,X.010.A.01-1.jpg
2,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,3,petlatl,05.02.03,X.010.A.03-1.jpg
3,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,4,cuahuitl_1,03.01.01,X.010.A.03-1.jpg
4,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,5,comitl,05.03.01,X.010.A.03-1.jpg

In [55]:
df.glyph_cote.value_counts()

glyph_cote
385_08v_01_01    19
385_08r_03_01    18
385_09r_09_01    18
385_08r_01_01    17
385_08r_02_01    17
                 ..
376_16r_17        1
376_16r_11        1
376_16r_04        1
376_16r_02        1
X.010.B.18        1
Name: count, Length: 23309, dtype: int64

In [56]:
df.glyph_cote.nunique()

23309

In [57]:
df_elem = pd.read_csv("elements.csv")
df_elem.head()

   id  codexid        cote          element  element_id     theme
0   1        1  X.010.A.01             tetl         584  04.04.01
1   2        1  X.010.A.01  xocpalmachiyotl         747  01.04.03
2   3        1  X.010.A.03          petlatl         472  05.02.03
3   4        1  X.010.A.03       cuahuitl_1         193  03.01.01
4   5        1  X.010.A.03           comitl         161  05.03.01

In [58]:
# Fast vectorized approach using map (no merge needed!)
# Create a dictionary mapping element name to element_id
element_to_id = df_elem.drop_duplicates('element').set_index('element')['element_id'].to_dict()

# Map element_name to element_id
df['element_id'] = df['element_name'].map(element_to_id)

print(f"Matched {df['element_id'].notna().sum()} out of {len(df)} rows")
print(f"\nUnmatched elements: {df['element_id'].isna().sum()}")
if df['element_id'].isna().any():
    print("\nSample unmatched element_names:")
    print(df[df['element_id'].isna()]['element_name'].unique()[:10])

Matched 44577 out of 44577 rows

Unmatched elements: 0

In [60]:
df.element_id.nunique()

785

In [59]:
df.isna().sum()

codex_id            0
codex_titre         0
glyph_id          578
glyph_cote          0
glyph_lecture    1137
element_id          0
element_name        0
element_theme       0
glyph_image         0
dtype: int64

In [62]:
df.glyph_id.astype('Int64')

0           1
1           1
2           2
3           2
4           2
         ...
44572    <NA>
44573    <NA>
44574    <NA>
44575    <NA>
44576    <NA>
Name: glyph_id, Length: 44577, dtype: Int64

In [63]:
df.to_csv("relationships_updated.csv")

In [65]:
df_class = pd.read_csv("relationships_updated.csv")
df.head(10)

,codex_id,codex_titre,glyph_id,glyph_cote,glyph_lecture,element_id,element_name,element_theme,glyph_image
0,1,XOLOTL,1.0,X.010.A.01,tenamitec,584,tetl,04.04.01,X.010.A.01-1.jpg
1,1,XOLOTL,1.0,X.010.A.01,tenamitec,747,xocpalmachiyotl,01.04.03,X.010.A.01-1.jpg
2,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,472,petlatl,05.02.03,X.010.A.03-1.jpg
3,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,193,cuahuitl_1,03.01.01,X.010.A.03-1.jpg
4,1,XOLOTL,2.0,X.010.A.03,cuauhchinanco,161,comitl,05.03.01,X.010.A.03-1.jpg
5,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,685,tototl,02.01.13,X.010.A.04-1.jpg
6,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,570,tepetl,04.03.08,X.010.A.04-1.jpg
7,1,XOLOTL,3.0,X.010.A.04,tototepec altepetl,75,atl,04.05.01,X.010.A.04-1.jpg
8,1,XOLOTL,4.0,X.010.B.01,zacatlan,776,zacatl,03.02.08,X.010.B.01-1.jpg
9,1,XOLOTL,4.0,X.010.B.01,zacatlan,624,tlanelhuatl,03.04.10,X.010.B.01-1.jpg

In [66]:
# ...existing code...
import pandas as pd

# load files
df = pd.read_csv('relationships.csv')
df_elem = pd.read_csv('elements.csv')

# map element names to element_id (fast, memory-efficient)
element_to_id = df_elem.drop_duplicates('element').set_index('element')['element_id'].to_dict()
df['element_id'] = df['element_name'].map(element_to_id)

# normalize cote and build glyph_image as "glyph_cote-codex_id.jpg"
df['glyph_cote'] = df['glyph_cote'].astype(str).str.replace('--', '-', regex=False)
df['glyph_image'] = df['glyph_cote'] + "-" + df['codex_id'].astype(str) + ".jpg"

# aggregate elements per glyph (unique, joined by |)
group_cols = ['codex_id', 'glyph_cote', 'glyph_id', 'glyph_lecture', 'glyph_image']
glyph_elements = (
    df.groupby(group_cols, dropna=False, sort=False)
      .agg(
          elements = ('element_name', lambda s: '|'.join(pd.unique(s.dropna().astype(str)))),
          element_ids = ('element_id', lambda s: '|'.join(pd.unique(s.dropna().astype(str))))
      )
      .reset_index()
)


glyph_elements.head(10)

,codex_id,glyph_cote,glyph_id,glyph_lecture,glyph_image,elements,element_ids
0,1,X.010.A.01,1.0,tenamitec,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,584|747
1,1,X.010.A.03,2.0,cuauhchinanco,X.010.A.03-1.jpg,petlatl|cuahuitl_1|comitl,472|193|161
2,1,X.010.A.04,3.0,tototepec altepetl,X.010.A.04-1.jpg,tototl|tepetl|atl,685|570|75
3,1,X.010.B.01,4.0,zacatlan,X.010.B.01-1.jpg,zacatl|tlanelhuatl,776|624
4,1,X.010.B.02,5.0,tolteca(tl),X.010.B.02-1.jpg,tolin|tentli,671|562
5,1,X.010.B.03-,6.0,tamazolac teopan zaca...,X.010.B.03--1.jpg,zacatl|tzacualli|tamazolin|atl|artefact_09,776|690|524|75|69
6,1,X.010.B.04,7.0,tlachia,X.010.B.04-1.jpg,ixtelolotli,326
7,1,X.010.B.08,8.0,...tepec,X.010.B.08-1.jpg,acatl|huitztli|tepetl,26|291|570
8,1,X.010.B.09,9.0,xolotl,X.010.B.09-1.jpg,xolotl,751
9,1,X.010.B.12,10.0,nopaltzin,X.010.B.12-1.jpg,nopalli,419

In [67]:
# save result
glyph_elements.to_csv('glyph_elements.csv', index=False)

In [ ]:
import os
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from typing import List, Optional

def make_multilabel_df(glyph_list: List[str],
                       glyph_key: str = 'glyph_cote',
                       glyph_elements_csv: str = 'glyph_elements.csv',
                       base_image_dir: str = './images',
                       use_element_ids: bool = False,
                       save_csv: Optional[str] = None) -> pd.DataFrame:
    """
    Build a multi-label dataframe for a list of glyphs.

    Parameters:
    - glyph_list: list of glyph identifiers (values of glyph_key) to keep
    - glyph_key: which column in glyph_elements.csv contains the glyph identifier
                 (e.g. 'glyph_cote' or 'glyph_image')
    - glyph_elements_csv: path to glyph_elements.csv (as attached)
    - base_image_dir: folder where your image files are stored; will be joined with glyph_image
    - use_element_ids: if True, build columns based on element_ids column; otherwise use element names
    - save_csv: optional path to save final dataframe as csv

    Returns:
    - final_df: DataFrame with columns: glyph_key, glyph_image, elements (original string),
                full_image_path, and one binary column per element
    """
    df = pd.read_csv(glyph_elements_csv, dtype=str).fillna('')

    # filter by provided glyph list
    df_filtered = df[df[glyph_key].isin(glyph_list)].copy()
    if df_filtered.empty:
        raise ValueError("No rows matched the provided glyph_list and glyph_key.")

    # choose which column to parse for labels
    label_col = 'element_ids' if use_element_ids else 'elements'

    # parse pipe-separated labels into lists (keep non-empty tokens)
    def parse_pipe(s):
        if not s or pd.isna(s):
            return []
        return [tok.strip() for tok in s.split('|') if tok.strip()]

    label_lists = df_filtered[label_col].apply(parse_pipe).tolist()

    # build binary matrix using MultiLabelBinarizer
    mlb = MultiLabelBinarizer(sparse_output=False)
    if len(label_lists) == 0 or all(len(l) == 0 for l in label_lists):
        # handle case with no labels: create empty mlb (no columns)
        labels_df = pd.DataFrame(index=df_filtered.index)
    else:
        labels_mat = mlb.fit_transform(label_lists)
        # prefix columns (optional) to avoid numeric-only column names issues
        if use_element_ids:
            col_names = [f"el_{c}" for c in mlb.classes_]
        else:
            # sanitize names (replace spaces, slashes), keep readable element names
            col_names = [str(c).replace(' ', '_').replace('/', '_') for c in mlb.classes_]
        labels_df = pd.DataFrame(data=labels_mat, columns=col_names, index=df_filtered.index)

    # add full image path (assuming glyph_image filename column exists)
    if 'glyph_image' in df_filtered.columns:
        df_filtered['full_image_path'] = df_filtered['glyph_image'].apply(
            lambda fn: os.path.join(base_image_dir, fn) if fn else '')
    else:
        df_filtered['full_image_path'] = ''

    # assemble final dataframe
    final_df = pd.concat([df_filtered[[glyph_key, 'glyph_image', label_col, 'full_image_path']].rename(
                              columns={label_col: 'elements_original'}),
                         labels_df], axis=1)

    # optional save
    if save_csv:
        final_df.to_csv(save_csv, index=False)

    return final_df

# 1) Hard-code glyph names you want to train on (glyph_cote values)


# 2) Directory where images you downloaded are stored
images_dir = f"f:\CODEX\AI_clinic\glyphs\{}"   # change to your local images folder

def make_image_dir(glyph_folder):
    images_dir = f"f:/CODEX/AI_clinic/glyphs/{glyph_folder}/"

# 3) Build dataframe using element names (set use_element_ids=True to use IDs)
df_multi = make_multilabel_df(glyph_list=glyphs_to_use,
                                glyph_key='glyph_cote',
                                glyph_elements_csv='glyph_elements.csv',
                                base_image_dir=make_image_dir(glyphs_dict),
                                use_element_ids=False,
                                save_csv='train_multilabel.csv')

print("Final shape:", df_multi.shape)

Final shape: (5, 14)
['glyph_cote', 'glyph_image', 'elements_original', 'full_image_path', 'atl', 'comitl', 'cuahuitl_1', 'petlatl', 'tepetl', 'tetl', 'tlantli', 'tototl', 'xocpalmachiyotl', 'zacatl']
     glyph_cote       glyph_image          elements_original  \
0    X.010.A.01  X.010.A.01-1.jpg       tetl|xocpalmachiyotl
1    X.010.A.03  X.010.A.03-1.jpg  petlatl|cuahuitl_1|comitl
2    X.010.A.04  X.010.A.04-1.jpg          tototl|tepetl|atl
339  X.020.A.01  X.020.A.01-1.jpg       tetl|xocpalmachiyotl
341  X.020.A.05  X.020.A.05-1.jpg             zacatl|tlantli

                                full_image_path  atl  comitl  cuahuitl_1  \
0    f:\CODEX\AI_clinic\images\X.010.A.01-1.jpg    0       0           0
1    f:\CODEX\AI_clinic\images\X.010.A.03-1.jpg    0       1           1
2    f:\CODEX\AI_clinic\images\X.010.A.04-1.jpg    1       0           0
339  f:\CODEX\AI_clinic\images\X.020.A.01-1.jpg    0       0           0
341  f:\CODEX\AI_clinic\images\X.020.A.05-1.jpg    0       0           0

     petlatl  tepetl  tetl  tlantli  tototl  xocpalmachiyotl  zacatl
0          0       0     1        0       0                1       0
1          1       0     0        0       0                0       0
2          0       1     0        0       1                0       0
339        0       0     1        0       0                1       0
341        0       0     0        1       0                0       1

In [69]:
df_multi.columns.tolist()

['glyph_cote',
 'glyph_image',
 'elements_original',
 'full_image_path',
 'atl',
 'comitl',
 'cuahuitl_1',
 'petlatl',
 'tepetl',
 'tetl',
 'tlantli',
 'tototl',
 'xocpalmachiyotl',
 'zacatl']

In [70]:
df_multi.head()

,glyph_cote,glyph_image,elements_original,full_image_path,atl,comitl,cuahuitl_1,petlatl,tepetl,tetl,tlantli,tototl,xocpalmachiyotl,zacatl
0,X.010.A.01,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,f:\CODEX\AI_clinic\images\X.010.A.01-1.jpg,0,0,0,0,0,1,0,0,1,0
1,X.010.A.03,X.010.A.03-1.jpg,petlatl|cuahuitl_1|comitl,f:\CODEX\AI_clinic\images\X.010.A.03-1.jpg,0,1,1,1,0,0,0,0,0,0
2,X.010.A.04,X.010.A.04-1.jpg,tototl|tepetl|atl,f:\CODEX\AI_clinic\images\X.010.A.04-1.jpg,1,0,0,0,1,0,0,1,0,0
339,X.020.A.01,X.020.A.01-1.jpg,tetl|xocpalmachiyotl,f:\CODEX\AI_clinic\images\X.020.A.01-1.jpg,0,0,0,0,0,1,0,0,1,0
341,X.020.A.05,X.020.A.05-1.jpg,zacatl|tlantli,f:\CODEX\AI_clinic\images\X.020.A.05-1.jpg,0,0,0,0,0,0,1,0,0,1

In [7]:
import os
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from typing import List, Optional, Dict

def make_multilabel_df(glyph_list: List[str],
                       glyph_key: str = 'glyph_cote',
                       glyph_elements_csv: str = 'glyph_elements.csv',
                       base_image_root: str = r'f:\CODEX\AI_clinic\glyphs',
                       glyph_folder_map: Optional[Dict[str, str]] = None,
                       use_element_ids: bool = False,
                       save_csv: Optional[str] = None) -> pd.DataFrame:
    """
    Build a multi-label dataframe for a list of glyphs.

    glyph_folder_map: optional dict mapping glyph identifier -> folder name where its images live.
                      If provided, full_image_path = os.path.join(base_image_root, folder, glyph_image).
                      Otherwise full_image_path = os.path.join(base_image_root, glyph_image).
    """
    df = pd.read_csv(glyph_elements_csv, dtype=str).fillna('')

    # filter by provided glyph list
    df_filtered = df[df[glyph_key].isin(glyph_list)].copy()
    if df_filtered.empty:
        raise ValueError("No rows matched the provided glyph_list and glyph_key.")

    # choose which column to parse for labels
    label_col = 'element_ids' if use_element_ids else 'elements'

    # parse pipe-separated labels into lists (keep non-empty tokens)
    def parse_pipe(s):
        if not s or pd.isna(s):
            return []
        return [tok.strip() for tok in s.split('|') if tok.strip()]

    label_lists = df_filtered[label_col].apply(parse_pipe).tolist()

    # build binary matrix using MultiLabelBinarizer
    mlb = MultiLabelBinarizer(sparse_output=False)
    if len(label_lists) == 0 or all(len(l) == 0 for l in label_lists):
        labels_df = pd.DataFrame(index=df_filtered.index)
    else:
        labels_mat = mlb.fit_transform(label_lists)
        if use_element_ids:
            col_names = [f"el_{c}" for c in mlb.classes_]
        else:
            col_names = [str(c).replace(' ', '_').replace('/', '_') for c in mlb.classes_]
        labels_df = pd.DataFrame(data=labels_mat, columns=col_names, index=df_filtered.index)

    # add full image path using optional per-glyph folder map
    def make_path(row):
        fn = row.get('glyph_image', '')
        if not fn:
            return ''
        glyph = row.get(glyph_key)
        if glyph_folder_map:
            folder = glyph_folder_map.get(glyph)
            if folder:
                return os.path.join(base_image_root, str(folder), fn)
        return os.path.join(base_image_root, fn)

    df_filtered['full_image_path'] = df_filtered.apply(make_path, axis=1)

    # assemble final dataframe
    final_df = pd.concat([df_filtered[[glyph_key, 'glyph_image', label_col, 'full_image_path']].rename(
                              columns={label_col: 'elements_original'}),
                         labels_df], axis=1)

    if save_csv:
        final_df.to_csv(save_csv, index=False)

    return final_df

# --- Example usage with dict mapping glyph -> folder name ---
# glyphs_dict = {
#     "032_05_003": "acatl-glyph",
#     "026r_A_07": "atl-glyph",
#     "032_05_005": "calli-glyph",
#     "026r_B_02": "chimalli-glyph",
#     "032_05_032": "cohuatl-glyph",
#     "032_05_024": "cuauhtli-glyph",
#     "027_05": "pantli-glyph",
#     "115_11_28": "tetl-glyph",
#     "032_05_012": "tochtli-glyph",
#     "385_17r_17_02": "xiuguitzolli-glyph"
# }

# glyph_list = list(glyphs_dict.keys())

# df_multi = make_multilabel_df(
#     glyph_list=glyph_list,
#     glyph_key='glyph_cote',
#     glyph_elements_csv='glyph_elements.csv',
#     base_image_root=r"f:\CODEX\AI_clinic\glyphs",   # root folder containing per-glyph folders
#     glyph_folder_map=glyphs_dict,
#     use_element_ids=False,
#     save_csv='train_multilabel.csv'
# )

# print("Final shape:", df_multi.shape)

In [75]:
df_multi.columns.tolist()

['glyph_cote',
 'glyph_image',
 'elements_original',
 'full_image_path',
 'acatl',
 'amatl',
 'apantli',
 'atl',
 'calli',
 'chimalli',
 'cohuatl',
 'cuauhtli',
 'cuexcochtechimalli',
 'eztli',
 'ihuitl',
 'ixcuatechimalli',
 'mitl',
 'pantli',
 'techimalli',
 'tenamitl',
 'tetl',
 'tochtli',
 'tomin',
 'tomin_2',
 'tzontli_2',
 'xihuitl_3',
 'xihuitl_4',
 'xiuhuitzolli']

In [83]:
df_multi

,glyph_cote,glyph_image,elements_original,full_image_path,acatl,amatl,apantli,atl,calli,chimalli,...,techimalli,tenamitl,tetl,tochtli,tomin,tomin_2,tzontli_2,xihuitl_3,xihuitl_4,xiuhuitzolli
2371,027_05,027_05-3.jpg,pantli|tomin|tomin_2,f:\CODEX\AI_clinic\glyphs\pantli-glyph\027_05-...,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
20693,026r_A_07,026r_A_07-2.jpg,atl|apantli,f:\CODEX\AI_clinic\glyphs\atl-glyph\026r_A_07-...,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20710,026r_B_02,026r_B_02-2.jpg,chimalli,f:\CODEX\AI_clinic\glyphs\chimalli-glyph\026r_...,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20786,032_05_003,032_05_003-6.jpg,acatl|mitl|ihuitl|apantli|xihuitl_4,f:\CODEX\AI_clinic\glyphs\acatl-glyph\032_05_0...,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20788,032_05_005,032_05_005-6.jpg,calli|xihuitl_4,f:\CODEX\AI_clinic\glyphs\calli-glyph\032_05_0...,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
20795,032_05_012,032_05_012-6.jpg,tochtli|xihuitl_4|eztli,f:\CODEX\AI_clinic\glyphs\tochtli-glyph\032_05...,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
20804,032_05_024,032_05_024-6.jpg,cuauhtli,f:\CODEX\AI_clinic\glyphs\cuauhtli-glyph\032_0...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20809,032_05_032,032_05_032-6.jpg,cohuatl,f:\CODEX\AI_clinic\glyphs\cohuatl-glyph\032_05...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21017,115_11_28,115_11_28-14.jpg,tetl|tenamitl,f:\CODEX\AI_clinic\glyphs\tetl-glyph\115_11_28...,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
22140,385_17r_17_02,385_17r_17_02-18.jpg,xiuhuitzolli|xihuitl_3|ixcuatechimalli|cuexcoc...,f:\CODEX\AI_clinic\glyphs\xiuguitzolli-glyph\3...,0,1,0,0,0,0,...,1,0,0,0,0,0,1,1,0,1

In [76]:
df_multi.head()

,glyph_cote,glyph_image,elements_original,full_image_path,acatl,amatl,apantli,atl,calli,chimalli,...,techimalli,tenamitl,tetl,tochtli,tomin,tomin_2,tzontli_2,xihuitl_3,xihuitl_4,xiuhuitzolli
2371,027_05,027_05-3.jpg,pantli|tomin|tomin_2,f:\CODEX\AI_clinic\glyphs\pantli-glyph\027_05-...,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
20693,026r_A_07,026r_A_07-2.jpg,atl|apantli,f:\CODEX\AI_clinic\glyphs\atl-glyph\026r_A_07-...,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20710,026r_B_02,026r_B_02-2.jpg,chimalli,f:\CODEX\AI_clinic\glyphs\chimalli-glyph\026r_...,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20786,032_05_003,032_05_003-6.jpg,acatl|mitl|ihuitl|apantli|xihuitl_4,f:\CODEX\AI_clinic\glyphs\acatl-glyph\032_05_0...,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20788,032_05_005,032_05_005-6.jpg,calli|xihuitl_4,f:\CODEX\AI_clinic\glyphs\calli-glyph\032_05_0...,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [79]:
for i in df_multi.full_image_path:
    print(i)

f:\CODEX\AI_clinic\glyphs\pantli-glyph\027_05-3.jpg
f:\CODEX\AI_clinic\glyphs\atl-glyph\026r_A_07-2.jpg
f:\CODEX\AI_clinic\glyphs\chimalli-glyph\026r_B_02-2.jpg
f:\CODEX\AI_clinic\glyphs\acatl-glyph\032_05_003-6.jpg
f:\CODEX\AI_clinic\glyphs\calli-glyph\032_05_005-6.jpg
f:\CODEX\AI_clinic\glyphs\tochtli-glyph\032_05_012-6.jpg
f:\CODEX\AI_clinic\glyphs\cuauhtli-glyph\032_05_024-6.jpg
f:\CODEX\AI_clinic\glyphs\cohuatl-glyph\032_05_032-6.jpg
f:\CODEX\AI_clinic\glyphs\tetl-glyph\115_11_28-14.jpg
f:\CODEX\AI_clinic\glyphs\xiuguitzolli-glyph\385_17r_17_02-18.jpg

In [8]:
# ...existing code...
import os
import glob
import pandas as pd

# root where per-glyph subfolders live
glyphs_root = r"f:\CODEX\AI_clinic\glyphs"

# find all JPG images under glyphs_root (recursively)
all_paths = glob.glob(os.path.join(glyphs_root, "**", "*.jpg"), recursive=True)
print(f"Found {len(all_paths)} image files under {glyphs_root}")

# local basename -> parent folder
local_parent = {os.path.basename(p): os.path.basename(os.path.dirname(p)) for p in all_paths}
local_basenames = list(local_parent.keys())

# read CSV and build lower->original lookup for glyph_image
df_g = pd.read_csv("../data_csv/glyph_elements.csv", dtype=str).fillna('')
csv_lookup = {name.lower(): name for name in df_g['glyph_image'].unique()}

# match local files to CSV (case-insensitive), build folder map keyed by CSV filename
matched = []
glyph_folder_map = {}
not_matched = []
for lb in local_basenames:
    key = lb.lower()
    if key in csv_lookup:
        csv_name = csv_lookup[key]
        matched.append(csv_name)
        glyph_folder_map[csv_name] = local_parent.get(lb, '')
    else:
        not_matched.append(lb)

print(f"Matches in glyph_elements.csv: {len(matched)} / {len(local_basenames)}")
if not_matched:
    print("Sample files not matched in CSV:", not_matched[:10])

# Use existing function to build multilabel DataFrame by glyph_image (pass CSV-original names)
df_multi = make_multilabel_df(
    glyph_list=matched,
    glyph_key='glyph_image',
    glyph_elements_csv='glyph_elements.csv',
    base_image_root=glyphs_root,
    glyph_folder_map=glyph_folder_map,
    use_element_ids=False,
    save_csv='train_multilabel_from_existing_images.csv'
)

print("Final shape:", df_multi.shape)
# ...existing code...

Found 0 image files in f:\CODEX\AI_clinic\glyphs
Matches in glyph_elements.csv: 0 / 0

FileNotFoundError: [Errno 2] No such file or directory: 'glyph_elements.csv'

In [92]:
df_multi.columns.tolist()

['glyph_image',
 'glyph_image',
 'elements_original',
 'full_image_path',
 '?',
 '?_02',
 '?_03',
 '?_04',
 '?_05',
 '?_07',
 'acalli',
 'acatl',
 'acocotli',
 'ahuictli',
 'ahuitzotl',
 'allacatl',
 'amanalli',
 'amatl',
 'ameyalli',
 'apantli',
 'apoctli',
 'apozonalli',
 'arbre_02',
 'artefact_05',
 'artefact_17',
 'atl',
 'atlacuetzonan',
 'ayatl',
 'ayotl',
 'ayotli',
 'aztatl',
 'barra',
 'borrado',
 'cacahuatl',
 'cacalotl',
 'cactli',
 'calacohuayan',
 'calcuamimilli',
 'calixtli',
 'calli',
 'camachalli',
 'canauhtli',
 'carga_de_yerba',
 'casa',
 'castillan_totolin',
 'caxitl',
 'ce',
 'cemixtlapalli',
 'centli',
 'centzontli',
 'chalchihuitl',
 'chapolin',
 'chian',
 'chichiquilli',
 'chilli',
 'chimalli',
 'chinamitl',
 'chitatli',
 'chocholli',
 'cihuatl',
 'cilli',
 'cipactli',
 'citlalin',
 'cohuatl',
 'coltic',
 'comitl',
 'conetl',
 'copilli',
 'corps_05',
 'corps_07',
 'cosmos_01',
 'cosmos_02',
 'coyoctic',
 'coyolli',
 'coyotl',
 'cozcatl',
 'cozolli',
 'coztic',
 'cruz',
 'cuacuahuitl',
 'cuahuitl_1',
 'cuahuitl_2',
 'cuaitl',
 'cuappantli',
 'cuauhcalli',
 'cuauhchayahualli',
 'cuauhtli',
 'cuauhtzotzontli',
 'cuaxicalli',
 'cuaxolotl',
 'cuechtli',
 'cuechtli_2',
 'cueitl',
 'cuetlachtli',
 'cuetlaxtli',
 'cuetzpalin',
 'cuexcochtechimalli',
 'cuexpalli',
 'cueyatl',
 'cuezalin',
 'cuezalpatzactli',
 'cuicuitzcatl',
 'cuitlatl',
 'effacé',
 'ehecacozcatl',
 'ehecatl',
 'ehuatl_1',
 'ehuatl_2',
 'epazotl',
 'etl',
 'explosión',
 'eztli',
 'flore_02',
 'flore_05',
 'friso',
 'huehuetl',
 'huei',
 'hueicalli',
 'huictli',
 'huipilli',
 'huitzilin',
 'huitzquilitl',
 'huitztli',
 'ichcahuipilli',
 'ichpochtli',
 'icopi',
 'icpalli',
 'icpatl',
 'icxitl',
 'ihuitl',
 'ithualli',
 'itztli',
 'ixayotl',
 'ixcuatechimalli',
 'ixnextlacuilolli',
 'ixtelolotli',
 'izquiztli',
 'iztac',
 'iztatl',
 'iztetl',
 'macpalli',
 'macuahuitl',
 'macuilli',
 'maitl_1',
 'maitl_2',
 'malinalli',
 'mamatlatl',
 'maquiztli',
 'matlactli',
 'matlalin',
 'matlalli',
 'maxaltic',
 'mazatl',
 'mecapalli',
 'mecatl',
 'metl',
 'metlapilli',
 'metlatl',
 'metztli',
 'michin',
 'micqui',
 'mitl',
 'mixoyotl',
 'mixtli',
 'mizquicuahuitl',
 'miztli',
 'molcaxitl',
 'molino',
 'momoyactli',
 'motivo_03',
 'nacaztli',
 'nenepilli',
 'neuccomitl',
 'nextli',
 'nocheztli',
 'nochtli',
 'nopalli',
 'ocelotl',
 'ococuahuitl',
 'octli',
 'ohuatl',
 'oiseau_02',
 'olli',
 'ornement_04',
 'otli',
 'ozomatli',
 'oztotl',
 'pantli',
 'papalotl',
 'parte_de_tronco',
 'patli',
 'pechtli',
 'petlacalli',
 'petlatl',
 'piedra_01',
 'piedra_3',
 'piqui',
 'plante_06',
 'plume_01',
 'popoca',
 'quadrupède_01',
 'quechtzontli',
 'quemitl',
 'quequetzalli',
 'quetzalli',
 'quetzalmiyahuayotl',
 'quimichin',
 'quimilli',
 'quiyahuatl',
 'quiyahuitl',
 'quiyotl',
 'rueda_hidráulica',
 'récipient_03',
 'récipient_04',
 'soporte_de_2_patas',
 'teapaztli',
 'techimalli',
 'tecihuitl',
 'tecololli',
 'tecolotl',
 'tecomatl',
 'tecpan',
 'tecpatl',
 'temazcalli',
 'tenamaztli',
 'tenamitl',
 'tenchilnahuayo',
 'tenextli',
 'tentetl',
 'tentlapilolli',
 'tentli',
 'teocuitlatl',
 'teopantli',
 'tepetl',
 'tepetla',
 'tepotzotli',
 'tepotztli',
 'tepoztli',
 'tepoztli_2',
 'terre_02',
 'tetl',
 'teuhtli',
 'texcalli',
 'texotli',
 'tezcatl',
 'tezontli',
 'tilmatli',
 'tlacatl',
 'tlachtli',
 'tlacotl',
 'tlacuatl',
 'tlacuilolli',
 'tlahuahuantli',
 'tlahuazomalli',
 'tlalacatl',
 'tlalli',
 'tlalpilli',
 'tlamamallahuiztli',
 'tlamamalli',
 'tlameme',
 'tlanelhuatl',
 'tlanextiliztli',
 'tlanextli',
 'tlantli',
 'tlaolli',
 'tlapalli',
 'tlapanqui',
 'tlapechtli',
 'tlatelli',
 'tlatoa',
 'tlaxichtli',
 'tlazolxochitl',
 'tlecuilli',
 'tlenamactli',
 'tletl',
 'tlilhuahuana',
 'tliltic',
 'tlotli',
 'tochtli',
 'tolin',
 'toloa',
 'tomin',
 'tomin_2',
 'tonalli',
 'tonatiuh',
 'topilli',
 'totolin',
 'tototl',
 'toztli',
 'tzacualli',
 'tzihuactli',
 'tzinacan',
 'tzintli',
 'tziuhtli',
 'tzontli',
 'tzontli_2',
 'variante_27',
 'xacalli',
 'xahualli',
 'xalli',
 'xamitl',
 'xapochtic',
 'xayacatl',
 'xicalcoliuhqui',
 'xicalli',
 'xicotli',
 'xihuitl_1',
 'xihuitl_3',
 'xihuitl_4',
 'xilotl',
 'xiquipilli',
 'xiuhtic',
 'xiuhuitzolli',
 'xochitl',
 'xocotl',
 'xocpalli',
 'xocpalmachiyotl',
 'xolochauhqui',
 'xolotl',
 'xonecuilli',
 'xoxomoltic',
 'yacametztli',
 'yacatl',
 'yahualiuhqui',
 'yahualli',
 'yauhtli',
 'yollotl',
 'yopitzontli',
 'zacatl',
 'zahuatl',
 'zayolin',
 'zo',
 'zolin',
 'zozoma']

In [95]:
df_multi.head()

,glyph_image,elements_original,full_image_path,?,?_02,?_03,?_04,?_05,?_07,acalli,...,yahualli,yauhtli,yollotl,yopitzontli,zacatl,zahuatl,zayolin,zo,zolin,zozoma
0,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,f:\CODEX\AI_clinic\glyphs\tetl-glyph\X.010.A.0...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,X.010.B.08-1.jpg,acatl|huitztli|tepetl,f:\CODEX\AI_clinic\glyphs\acatl-glyph\X.010.B....,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,X.010.B.19-1.jpg,pantli|oztotl,f:\CODEX\AI_clinic\glyphs\pantli-glyph\X.010.B...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,X.010.B.23-1.jpg,tetl|oztotl|petlatl,f:\CODEX\AI_clinic\glyphs\tetl-glyph\X.010.B.2...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,X.010.D.05-1.jpg,cohuatl|quimilli,f:\CODEX\AI_clinic\glyphs\cohuatl-glyph\X.010....,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [94]:
df_multi = df_multi.iloc[:, 1:]

In [96]:
df_multi.to_csv("training_data.csv")

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data_csv/train_multilabel_from_existing_images.csv")

In [3]:
df.head()

,glyph_image,glyph_image.1,elements_original,full_image_path,?,?_02,?_03,?_04,?_05,?_07,...,yahualli,yauhtli,yollotl,yopitzontli,zacatl,zahuatl,zayolin,zo,zolin,zozoma
0,X.010.A.01-1.jpg,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,f:\CODEX\AI_clinic\glyphs\tetl-glyph\X.010.A.0...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,X.010.B.08-1.jpg,X.010.B.08-1.jpg,acatl|huitztli|tepetl,f:\CODEX\AI_clinic\glyphs\acatl-glyph\X.010.B....,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,X.010.B.19-1.jpg,X.010.B.19-1.jpg,pantli|oztotl,f:\CODEX\AI_clinic\glyphs\pantli-glyph\X.010.B...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,X.010.B.23-1.jpg,X.010.B.23-1.jpg,tetl|oztotl|petlatl,f:\CODEX\AI_clinic\glyphs\tetl-glyph\X.010.B.2...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,X.010.D.05-1.jpg,X.010.D.05-1.jpg,cohuatl|quimilli,f:\CODEX\AI_clinic\glyphs\cohuatl-glyph\X.010....,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
import os
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# Read the CSV with glyph elements
df_g = pd.read_csv("../data_csv/glyph_elements.csv", dtype=str).fillna('')

# Path to glyphs folder (relative)
glyphs_folder = "glyphs\Unsorted"

# Function to check if image exists and build path
def build_image_path(glyph_image):
    if not glyph_image:
        return float('nan')
    
    full_path = os.path.join(glyphs_folder, glyph_image)
    
    # Check if file exists (using absolute path for checking)
    abs_check_path = os.path.join(r"f:\CODEX\AI_clinic_class", full_path)
    if os.path.exists(abs_check_path):
        return full_path
    else:
        return float('nan')

# Parse pipe-separated elements into lists
def parse_pipe(s):
    if not s or pd.isna(s):
        return []
    return [tok.strip() for tok in s.split('|') if tok.strip()]

# Parse elements into label lists
label_lists = df_g['elements'].apply(parse_pipe).tolist()

# Build binary matrix using MultiLabelBinarizer
mlb = MultiLabelBinarizer(sparse_output=False)
labels_mat = mlb.fit_transform(label_lists)

# Sanitize column names
col_names = [str(c).replace(' ', '_').replace('/', '_') for c in mlb.classes_]
labels_df = pd.DataFrame(data=labels_mat, columns=col_names, index=df_g.index)

# Build full_image_path column
df_g['full_image_path'] = df_g['glyph_image'].apply(build_image_path)

# Assemble final dataframe
final_df = pd.concat([
    df_g[['glyph_image', 'elements', 'full_image_path']].rename(columns={'elements': 'elements_original'}),
    labels_df
], axis=1)

# Save to CSV
output_path = "../data_csv/training_data_relative_paths.csv"
final_df.to_csv(output_path, index=False)

print(f"Final shape: {final_df.shape}")
print(f"Saved to: {output_path}")
print(f"Images found: {final_df['full_image_path'].notna().sum()} / {len(final_df)}")

Final shape: (23309, 788)
Saved to: ../data_csv/training_data_relative_paths.csv
Images found: 4992 / 23309

In [12]:
len(final_df)

23309

In [14]:
# Remove rows where full_image_path is NaN (no image exists)
final_df = final_df[final_df['full_image_path'].notna()]

# Re-save the filtered CSV
output_path = "../data_csv/training_data_relative_paths.csv"
final_df.to_csv(output_path, index=False)

print(f"Final shape after removing NaN: {final_df.shape}")
print(f"Saved filtered data to: {output_path}")

final_df

Final shape after removing NaN: (4992, 788)
Saved filtered data to: ../data_csv/training_data_relative_paths.csv

,glyph_image,elements_original,full_image_path,20,21?,?,??,?_01,?_02,?_03,...,zacatl,zacuan,zahualli,zahuatl,zayolin,zo,zolin,zoquitl,zoyatl,zozoma
0,X.010.A.01-1.jpg,tetl|xocpalmachiyotl,glyphs/Unsorted\X.010.A.01-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,X.010.B.08-1.jpg,acatl|huitztli|tepetl,glyphs/Unsorted\X.010.B.08-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,X.010.B.12-1.jpg,nopalli,glyphs/Unsorted\X.010.B.12-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,X.010.B.19-1.jpg,pantli|oztotl,glyphs/Unsorted\X.010.B.19-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,X.010.B.23-1.jpg,tetl|oztotl|petlatl,glyphs/Unsorted\X.010.B.23-1.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23299,376_13r_12-17.jpg,cuauhtli,glyphs/Unsorted\376_13r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23300,376_14r_06-17.jpg,cuauhtli,glyphs/Unsorted\376_14r_06-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23301,376_14r_12-17.jpg,cuauhtli,glyphs/Unsorted\376_14r_12-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23302,376_21v_01-17.jpg,cuauhtli,glyphs/Unsorted\376_21v_01-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23303,376_21v_17-17.jpg,cuauhtli,glyphs/Unsorted\376_21v_17-17.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0